// Generated by scripts/record-server.mjs from assets/audio/<lang>/. Do not edit.
/** Recorded clips: language -> label text -> file. @type {Record<string, Record<string, string>>} */
export const clips = {
  ka: {
    "ვაშლი": "assets/audio/ka/apple.wav",
  },
};
