// Generated by scripts/record-server.mjs from assets/audio/<lang>/<voice>/. Do not edit.
/** Recorded clips: language -> voice -> label text -> file. @type {Record<string, Record<string, Record<string, string>>>} */
export const clips = {
  ka: {
    male: {
      "ვაშლი": "assets/audio/ka/male/apple.wav",
    },
  },
};
